// next-app/src/components/func-area.tsx
"use client";

import { useEffect, useState } from "react";
import { getCurrentTime, type CurrentTime } from "@/lib/get-time";
import { siteConfig } from "@/lib/config";
import { useMain } from "@/store/main";
import { Hitokoto } from "./hitokoto";
import { MusicPanel } from "./music-panel";
import { Weather } from "./weather";
import { Card } from "@/components/ui/card";

export function FuncArea() {
  const mobileFuncState = useMain((s) => s.mobileFuncState);
  const hasSong = !!siteConfig.songId;

  const [now, setNow] = useState<CurrentTime>(() => getCurrentTime());
  useEffect(() => {
    const id = setInterval(() => setNow(getCurrentTime()), 1000);
    return () => clearInterval(id);
  }, []);

  return (
    <div className="h-[165px] flex items-center justify-between gap-5">
      <div className={`flex-1 h-full ${mobileFuncState ? "block" : "hidden md:block"}`}>
        <div className="h-full w-full relative">
          <Hitokoto />
          {hasSong && (
            <div className="absolute inset-0 pointer-events-none [&>*]:pointer-events-auto">
              <MusicPanel />
            </div>
          )}
        </div>
      </div>
      <div className={`flex-1 h-full ${mobileFuncState ? "hidden md:block" : "block"}`}>
        <Card className="h-full w-full flex flex-col items-center justify-between p-5 animate-fade-in">
          <div className="text-center">
            <div className="truncate">
              <span>{now.year}&nbsp;年&nbsp;</span>
              <span>{now.month}&nbsp;月&nbsp;</span>
              <span>{now.day}&nbsp;日&nbsp;</span>
              <span className="hidden sm:inline">{now.weekday}</span>
            </div>
            <div className="mt-2.5 text-5xl tracking-wider font-led">
              {now.hour}:{now.minute}:{now.second}
            </div>
          </div>
          <Weather />
        </Card>
      </div>
    </div>
  );
}

// app/components/FuncArea.vue
<template>
  <!-- 功能区域 -->
  <div :class="store.mobileFuncState ? 'function mobile' : 'function'">
    <el-row :gutter="20">
      <el-col :span="12">
        <div class="left">
          <Hitokoto />
          <MusicPanel v-if="playerHasId" />
        </div>
      </el-col>
      <el-col :span="12">
        <div class="right cards">
          <div class="time">
            <div class="date">
              <span>{{ currentTime.year }}&nbsp;年&nbsp;</span>
              <span>{{ currentTime.month }}&nbsp;月&nbsp;</span>
              <span>{{ currentTime.day }}&nbsp;日&nbsp;</span>
              <span class="sm-hidden">{{ currentTime.weekday }}</span>
            </div>
            <div class="text">
              <span> {{ currentTime.hour }}:{{ currentTime.minute }}:{{ currentTime.second }}</span>
            </div>
          </div>
          <Weather />
        </div>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
import { getCurrentTime } from "~/utils/getTime";

const store = mainStore();
const config = useRuntimeConfig();

// 当前时间
const currentTime = ref({});
const timeInterval = ref(null);

// 播放器 id
const playerHasId = config.public.songId;

// 更新时间
const updateTimeData = () => {
  currentTime.value = getCurrentTime();
};

onMounted(() => {
  updateTimeData();
  timeInterval.value = setInterval(updateTimeData, 1000);
});

onBeforeUnmount(() => {
  clearInterval(timeInterval.value);
});
</script>

<style lang="scss" scoped>
.function {
  height: 165px;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-between;
  &.mobile {
    .el-row {
      .el-col {
        &:nth-of-type(1) {
          display: contents;
        }
        &:nth-of-type(2) {
          display: none;
        }
      }
    }
  }
  .el-row {
    height: 100%;
    width: 100%;
    margin: 0 !important;
    .el-col {
      &:nth-of-type(1) {
        padding-left: 0 !important;
      }
      &:nth-of-type(2) {
        padding-right: 0 !important;
      }
      @media (max-width: 910px) {
        &:nth-of-type(1) {
          display: none;
        }
        &:nth-of-type(2) {
          padding: 0 !important;
          flex: none;
          max-width: none;
          width: 100%;
        }
      }
    }
    .left,
    .right {
      width: 100%;
      height: 100%;
    }
    .right {
      padding: 20px;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: space-between;
      animation: fade 0.5s;
      .time {
        font-size: 1.1rem;
        text-align: center;
        .date {
          text-overflow: ellipsis;
          overflow-x: hidden;
          white-space: nowrap;
        }
        .text {
          margin-top: 10px;
          font-size: 3.25rem;
          letter-spacing: 2px;
          font-family: "UnidreamLED";
        }
        @media (min-width: 1201px) and (max-width: 1280px) {
          font-size: 1rem;
        }
        @media (min-width: 911px) and (max-width: 992px) {
          font-size: 1rem;
          .text {
            font-size: 2.75rem;
          }
        }
      }
      .weather {
        text-align: center;
        width: 100%;
        text-overflow: ellipsis;
        overflow-x: hidden;
        white-space: nowrap;
      }
    }
  }
}
</style>
