// next-app/src/components/settings-panel.tsx
"use client";

import { toast } from "sonner";
import { CircleCheck } from "lucide-react";
import { useMain, THEME_STYLES, type ThemeStyle } from "@/store/main";
import {
  Accordion, AccordionItem, AccordionTrigger, AccordionContent,
} from "@/components/ui/accordion";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Switch } from "@/components/ui/switch";

const THEME_COLOR: Record<ThemeStyle, string> = {
  zinc: "#52525b", slate: "#475569", stone: "#57534e", gray: "#4b5563",
  neutral: "#525252", red: "#dc2626", rose: "#e11d48", orange: "#f97316",
  green: "#16a34a", blue: "#2563eb", yellow: "#eab308", violet: "#7c3aed",
};

export function SettingsPanel() {
  const s = useMain((st) => st);
  const set = useMain((st) => st.set);

  return (
    <div className="text-white">
      <Accordion type="single" collapsible defaultValue="1" className="w-full">
        <AccordionItem value="1">
          <AccordionTrigger>个性壁纸</AccordionTrigger>
          <AccordionContent>
            <RadioGroup
              value={s.coverType}
              onValueChange={(v) => {
                set("coverType", v as typeof s.coverType);
                toast("壁纸更换成功", { icon: <CircleCheck size={18} /> });
              }}
              className="grid-cols-2 sm:grid-cols-4"
            >
              <RadioGroupItem value="0" label="默认壁纸" />
              <RadioGroupItem value="1" label="每日一图" />
              <RadioGroupItem value="2" label="随机风景" />
              <RadioGroupItem value="3" label="随机动漫" />
            </RadioGroup>
          </AccordionContent>
        </AccordionItem>

        <AccordionItem value="theme">
          <AccordionTrigger>主题色</AccordionTrigger>
          <AccordionContent className="space-y-3">
            <div className="flex items-center justify-between text-sm">
              <span>跟随系统随机（每次打开随机主题色）</span>
              <Switch
                checked={s.themeStyle === null}
                onCheckedChange={(c) => set("themeStyle", c ? null : "zinc")}
              />
            </div>
            {s.themeStyle !== null && (
              <div className="grid grid-cols-6 gap-2.5">
                {THEME_STYLES.map((t) => {
                  const selected = s.themeStyle === t;
                  return (
                    <button
                      key={t}
                      type="button"
                      aria-label={`主题色 ${t}`}
                      aria-pressed={selected}
                      onClick={() => set("themeStyle", t)}
                      className={`focus-ring relative h-10 rounded-md border-2 transition-all ${
                        selected
                          ? "border-white scale-105 shadow-lg"
                          : "border-white/20 hover:border-white/60 hover:scale-105"
                      }`}
                      style={{ background: THEME_COLOR[t] }}
                      title={t}
                    >
                      {selected && (
                        <CircleCheck
                          size={16}
                          aria-hidden
                          className="absolute inset-0 m-auto text-white drop-shadow"
                        />
                      )}
                    </button>
                  );
                })}
              </div>
            )}
            <div className="text-xs text-white/60">浅色 / 深色 自动跟随系统。</div>
          </AccordionContent>
        </AccordionItem>

        <AccordionItem value="2">
          <AccordionTrigger>个性化调整</AccordionTrigger>
          <AccordionContent className="space-y-3">
            <Row label="建站日期显示" checked={s.siteStartShow} onChange={(v) => set("siteStartShow", v)} />
            <Row label="音乐点击是否打开面板" checked={s.musicClick} onChange={(v) => set("musicClick", v)} />
            <Row label="底栏歌词显示" checked={s.playerLrcShow} onChange={(v) => set("playerLrcShow", v)} />
            <Row label="底栏背景模糊" checked={s.footerBlur} onChange={(v) => set("footerBlur", v)} />
          </AccordionContent>
        </AccordionItem>

        <AccordionItem value="3">
          <AccordionTrigger>播放器配置</AccordionTrigger>
          <AccordionContent className="space-y-3">
            <Row label="自动播放" checked={s.playerAutoplay} onChange={(v) => set("playerAutoplay", v)} />
            <Row
              label="随机播放"
              checked={s.playerOrder === "random"}
              onChange={(v) => set("playerOrder", v ? "random" : "list")}
            />
            <div>
              <div className="mb-2 text-sm">循环模式</div>
              <RadioGroup
                value={s.playerLoop}
                onValueChange={(v) => set("playerLoop", v as typeof s.playerLoop)}
                className="grid-cols-3"
              >
                <RadioGroupItem value="all" label="列表" />
                <RadioGroupItem value="one" label="单曲" />
                <RadioGroupItem value="none" label="不循环" />
              </RadioGroup>
            </div>
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    </div>
  );
}

function Row({ label, checked, onChange }: { label: string; checked: boolean; onChange: (v: boolean) => void }) {
  return (
    <div className="flex items-center justify-between text-sm">
      <span>{label}</span>
      <Switch checked={checked} onCheckedChange={onChange} />
    </div>
  );
}

// app/components/SettingsPanel.vue
<template>
  <div class="setting">
    <el-collapse v-model="activeName" class="collapse" accordion>
      <el-collapse-item title="个性壁纸" name="1">
        <div class="bg-set">
          <el-radio-group v-model="coverType" text-color="#ffffff" @change="radioChange">
            <el-radio value="0" size="large" border>默认壁纸</el-radio>
            <el-radio value="1" size="large" border>每日一图</el-radio>
            <el-radio value="2" size="large" border>随机风景</el-radio>
            <el-radio value="3" size="large" border>随机动漫</el-radio>
          </el-radio-group>
        </div>
      </el-collapse-item>
      <el-collapse-item title="个性化调整" name="2">
        <div class="item">
          <span class="text">建站日期显示</span>
          <el-switch
            v-model="siteStartShow"
            inline-prompt
            :active-icon="Check"
            :inactive-icon="X"
          />
        </div>
        <div class="item">
          <span class="text">音乐点击是否打开面板</span>
          <el-switch
            v-model="musicClick"
            inline-prompt
            :active-icon="Check"
            :inactive-icon="X"
          />
        </div>
        <div class="item">
          <span class="text">底栏歌词显示</span>
          <el-switch
            v-model="playerLrcShow"
            inline-prompt
            :active-icon="Check"
            :inactive-icon="X"
          />
        </div>
        <div class="item">
          <span class="text">底栏背景模糊</span>
          <el-switch
            v-model="footerBlur"
            inline-prompt
            :active-icon="Check"
            :inactive-icon="X"
          />
        </div>
      </el-collapse-item>
      <el-collapse-item title="播放器配置" name="3">
        <div class="item">
          <span class="text">自动播放</span>
          <el-switch
            v-model="playerAutoplay"
            inline-prompt
            :active-icon="Check"
            :inactive-icon="X"
          />
        </div>
        <div class="item">
          <span class="text">随机播放</span>
          <el-switch
            v-model="playerOrder"
            inline-prompt
            :active-icon="Check"
            :inactive-icon="X"
            active-value="random"
            inactive-value="list"
          />
        </div>
        <div class="item">
          <span class="text">循环模式</span>
          <el-radio-group v-model="playerLoop" size="small" text-color="#FFFFFF">
            <el-radio value="all" border>列表</el-radio>
            <el-radio value="one" border>单曲</el-radio>
            <el-radio value="none" border>不循环</el-radio>
          </el-radio-group>
        </div>
      </el-collapse-item>
      <el-collapse-item title="其他设置" name="4">
        <div>设置内容待增加</div>
      </el-collapse-item>
    </el-collapse>
  </div>
</template>

<script setup lang="ts">
import { Check, X, CircleCheck } from "lucide-vue-next";
import { storeToRefs } from "pinia";

const store = mainStore();
const {
  coverType,
  siteStartShow,
  musicClick,
  playerLrcShow,
  footerBlur,
  playerAutoplay,
  playerOrder,
  playerLoop,
} = storeToRefs(store);

// 默认选中项
const activeName = ref("1");

// 壁纸切换
const radioChange = () => {
  ElMessage({
    message: "壁纸更换成功",
    icon: h(CircleCheck, { size: 20, color: "#efefef" }),
  });
};
</script>

<style lang="scss" scoped>
.setting {
  .collapse {
    border-radius: 8px;
    --el-collapse-content-bg-color: #ffffff10;
    border-color: transparent;
    overflow: hidden;

    :deep(.el-collapse-item__header) {
      background-color: #ffffff30;
      color: #fff;
      font-size: 15px;
      padding-left: 18px;
      border-color: transparent;
    }

    :deep(.el-collapse-item__wrap) {
      border-color: transparent;

      .el-collapse-item__content {
        padding: 20px;
        .item {
          display: flex;
          align-items: center;
          justify-content: space-between;
          flex-wrap: wrap;
          font-size: 14px;
          .el-switch__core {
            border-color: transparent;
            background-color: #ffffff30;
          }
          .el-radio-group {
            .el-radio {
              margin: 2px 10px 2px 0;
              border-radius: 5px;

              &:last-child {
                margin-right: 0;
              }
            }
          }
        }
        .el-radio-group {
          justify-content: space-between;

          .el-radio {
            margin: 10px 16px;
            background: #ffffff26;
            border: 2px solid transparent;
            border-radius: 8px;

            .el-radio__label {
              color: #fff;
            }

            .el-radio__inner {
              background: #ffffff06 !important;
              border: 2px solid #eeeeee !important;
            }

            &.is-checked {
              background: #ffffff06 !important;
              border: 2px solid #eeeeee !important;
            }

            .is-checked {
              .el-radio__label {
                color: #fff !important;
              }

              .el-radio__inner {
                background-color: #ffffff30 !important;
                border-color: #fff !important;
              }

              & + .el-radio__label {
                color: #fff !important;
              }
            }
          }
        }
      }
    }
  }
}
</style>
