// app/components/Hitokoto.vue
<template>
  <div
    v-show="!store.musicOpenState"
    class="hitokoto cards"
    @mouseenter="openMusicShow = true"
    @mouseleave="openMusicShow = false"
    @click.stop
  >
    <!-- 打开音乐面板 -->
    <Transition name="el-fade-in-linear">
      <div
        v-show="(openMusicShow || isMobile) && store.musicIsOk"
        class="open-music"
        @click="store.musicOpenState = true"
      >
        <ListMusic :size="18" color="#efefef" />
        <span>打开音乐播放器</span>
      </div>
    </Transition>
    <!-- 一言内容 -->
    <Transition name="el-fade-in-linear" mode="out-in">
      <div :key="hitokotoData.text" class="content" @click="updateHitokoto">
        <span class="text">{{ hitokotoData.text }}</span>
        <span class="from">-「&nbsp;{{ hitokotoData.from }}&nbsp;」</span>
      </div>
    </Transition>
  </div>
</template>

<script setup lang="ts">
import { ListMusic, CircleAlert } from "lucide-vue-next";
import debounce from "~/utils/debounce";

const store = mainStore();
const { getHitokoto } = useApi();

const isMobile = computed(() => store.innerWidth !== null && store.innerWidth < 721);

// 开启音乐面板按钮显隐
const openMusicShow = ref(false);

// 一言数据
const hitokotoData = reactive({
  text: "这里应该显示一句话",
  from: "無名",
});

// 获取一言数据
const getHitokotoData = async () => {
  try {
    const result = (await getHitokoto()) as { hitokoto: string; from: string };
    hitokotoData.text = result.hitokoto;
    hitokotoData.from = result.from;
  } catch {
    ElMessage({
      message: "一言获取失败",
      icon: h(CircleAlert, { size: 20, color: "#efefef" }),
    });
    hitokotoData.text = "这里应该显示一句话";
    hitokotoData.from = "無名";
  }
};

// 更新一言数据
const updateHitokoto = () => {
  debounce(() => {
    getHitokotoData();
  }, 500);
};

onMounted(() => {
  getHitokotoData();
});
</script>

<style lang="scss" scoped>
.hitokoto {
  width: 100%;
  height: 100%;
  padding: 20px;
  animation: fade 0.5s;
  .open-music {
    width: 100%;
    position: absolute;
    top: 0;
    left: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    background: #00000026;
    padding: 4px 0;
    border-radius: 8px 8px 0 0;
    .i-icon {
      width: 18px;
      height: 18px;
      display: block;
      margin-right: 8px;
    }
    span {
      font-size: 0.95rem;
    }
  }
  .content {
    height: 100%;
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
    .text {
      font-size: 1.1rem;
      word-break: break-all;
      text-overflow: ellipsis;
      overflow: hidden;
      display: -webkit-box;
      -webkit-line-clamp: 3;
      -webkit-box-orient: vertical;
    }
    .from {
      margin-top: 10px;
      font-weight: bold;
      align-self: flex-end;
      font-size: 1.1rem;
    }
  }
}
</style>

// next-app/src/components/hitokoto.tsx
"use client";

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { CircleAlert, ListMusic } from "lucide-react";
import { toast } from "sonner";
import { debounce } from "@/lib/debounce";
import { getHitokoto } from "@/lib/api";
import { useMain } from "@/store/main";
import { useIsMobile } from "@/hooks/use-mobile";
import { Card } from "@/components/ui/card";

export function Hitokoto() {
  const musicOpen = useMain((s) => s.musicOpenState);
  const musicIsOk = useMain((s) => s.musicIsOk);
  const setStore = useMain((s) => s.set);
  const isMobile = useIsMobile();

  const [data, setData] = useState({ text: "这里应该显示一句话", from: "無名" });
  const [hover, setHover] = useState(false);

  const fetchData = async () => {
    try {
      const r = await getHitokoto();
      setData({ text: r.hitokoto, from: r.from });
    } catch {
      toast("一言获取失败", { icon: <CircleAlert size={18} /> });
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  if (musicOpen) return null;

  return (
    <Card
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      onClick={() => debounce(fetchData, 500)}
      className="relative h-full w-full p-5 cursor-pointer animate-fade-in"
    >
      <AnimatePresence>
        {(hover || isMobile) && musicIsOk && (
          <motion.button
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={(e) => {
              e.stopPropagation();
              setStore("musicOpenState", true);
            }}
            className="absolute top-0 left-0 w-full flex items-center justify-center gap-2 bg-black/20 py-1 rounded-t-2xl text-sm"
          >
            <ListMusic size={18} />
            <span>打开音乐播放器</span>
          </motion.button>
        )}
      </AnimatePresence>
      <AnimatePresence mode="wait">
        <motion.div
          key={data.text}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="h-full flex flex-col justify-evenly"
        >
          <span className="text-[1.1rem] break-all line-clamp-3">{data.text}</span>
          <span className="mt-2.5 font-bold self-end text-[1.1rem]">-「&nbsp;{data.from}&nbsp;」</span>
        </motion.div>
      </AnimatePresence>
    </Card>
  );
}
