// app/components/MainRight.vue
<template>
  <div :class="store.mobileOpenState ? 'right' : 'right hidden'">
    <!-- 移动端 Logo -->
    <div class="logo text-hidden" @click="store.mobileFuncState = !store.mobileFuncState">
      <span class="bg">{{ siteUrl[0] }}</span>
      <span class="sm">.{{ siteUrl[1] }}</span>
    </div>
    <!-- 功能区 -->
    <FuncArea />
    <!-- 网站链接 -->
    <Links />
  </div>
</template>

<script setup lang="ts">
const store = mainStore();
const config = useRuntimeConfig();

// 站点链接
const siteUrl = computed(() => {
  const url = config.public.siteUrl;
  if (!url) return "saop.cc".split(".");
  if (url.startsWith("http://") || url.startsWith("https://")) {
    const urlFormat = url.replace(/^(https?:\/\/)/, "");
    return urlFormat.split(".");
  }
  return url.split(".");
});
</script>

<style lang="scss" scoped>
.right {
  width: 50%;
  margin-left: 0.75rem;
  .logo {
    width: 100%;
    font-family: "Pacifico-Regular";
    font-size: 2.25rem;
    position: fixed;
    top: 6%;
    left: 0;
    text-align: center;
    transition: transform 0.3s;
    animation: fade 0.5s;
    &:active {
      transform: scale(0.95);
    }
    @media (min-width: 721px) {
      display: none;
    }
    @media (max-height: 720px) {
      width: calc(100% + 6px);
      top: 43.26px;
    }
    @media (max-width: 390px) {
        width: 391px;
    }
  }
  @media (max-width: 720px) {
    margin-left: 0;
    width: 100%;
    &.hidden {
      display: none;
    }
  }
}
</style>

// next-app/src/components/main-right.tsx
"use client";

import { useMemo } from "react";
import { siteConfig } from "@/lib/config";
import { useMain } from "@/store/main";
import { FuncArea } from "./func-area";
import { Links } from "./links";

function parseUrl(raw: string): [string, string] {
  const url = raw || "saop.cc";
  const clean = url.replace(/^(https?:\/\/)/, "");
  const parts = clean.split(".");
  return [parts[0] ?? "saop", parts.slice(1).join(".") || "cc"];
}

export function MainRight() {
  const mobileOpen = useMain((s) => s.mobileOpenState);
  const setStore = useMain((s) => s.set);
  const funcState = useMain((s) => s.mobileFuncState);
  const [name, tld] = useMemo(() => parseUrl(siteConfig.siteUrl), []);

  return (
    <div className={`md:w-1/2 md:ml-3 w-full ${mobileOpen ? "block" : "hidden md:block"}`}>
      <div
        onClick={() => setStore("mobileFuncState", !funcState)}
        className="w-full font-pacifico text-center text-4xl fixed top-[6%] left-0 transition-transform active:scale-95 animate-fade-in md:hidden truncate px-4"
      >
        <span>{name}</span>
        <span>.{tld}</span>
      </div>
      <FuncArea />
      <Links />
    </div>
  );
}
