// app/components/Message.vue
<template>
  <!-- 基本信息 -->
  <div class="message">
    <!-- Logo -->
    <div class="logo">
      <img class="logo-img" :src="config.public.siteMainLogo" alt="logo" >
      <div class="name text-hidden" :class="{ long: siteUrl[0]!.length >= 6 }">
        <span class="bg">{{ siteUrl[0] }}</span>
        <span class="sm">.{{ siteUrl[1] }}</span>
      </div>
    </div>
    <!-- 简介 -->
    <div class="description cards" @click="changeBox">
      <div class="content">
        <Quote :size="16" color="#fff" />
        <Transition name="fade" mode="out-in">
          <div :key="descriptionText.hello + descriptionText.text" class="text">
            <p>{{ descriptionText.hello }}</p>
            <p>{{ descriptionText.text }}</p>
          </div>
        </Transition>
        <Quote :size="16" color="#fff" class="quote-flip" />
      </div>
      <Transition name="fade">
        <div v-if="sitePv !== null" class="site-count">
          <Eye :size="12" />
          <span>{{ sitePv }}</span>
          <Users :size="12" />
          <span>{{ siteUv }}</span>
        </div>
      </Transition>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Quote, Eye, Users } from "lucide-vue-next";
import { useBusuanzi } from "~/composables/useBusuanzi";

const store = mainStore();
const config = useRuntimeConfig();
const { sitePv, siteUv } = useBusuanzi();

// 站点链接
const siteUrl = computed(() => {
  const url = config.public.siteUrl;
  if (!url) return "saop.cc".split(".");
  if (url.startsWith("http://") || url.startsWith("https://")) {
    const urlFormat = url.replace(/^(https?:\/\/)/, "");
    return urlFormat.split(".");
  }
  return url.split(".");
});

// 简介区域文字
const descriptionText = reactive({
  hello: config.public.descHello,
  text: config.public.descText,
});

// 切换右侧功能区
const changeBox = () => {
  store.boxOpenState = !store.boxOpenState;
};

// 监听状态变化
watch(
  () => store.boxOpenState,
  (value) => {
    if (value) {
      descriptionText.hello = config.public.descHelloOther;
      descriptionText.text = config.public.descTextOther;
    } else {
      descriptionText.hello = config.public.descHello;
      descriptionText.text = config.public.descText;
    }
  },
);
</script>

<style lang="scss" scoped>
.message {
  .logo {
    display: flex;
    flex-direction: row;
    align-items: center;
    animation: fade 0.5s;
    max-width: 460px;
    .logo-img {
      border-radius: 50%;
      width: 120px;
    }
    .name {
      width: 100%;
      padding-left: 22px;
      transform: translateY(-8px);
      font-family: "Pacifico-Regular";

      .bg {
        font-size: 5rem;
      }

      .sm {
        margin-left: 6px;
        font-size: 2rem;
        @media (min-width: 721px) and (max-width: 789px) {
          display: none;
        }
      }
    }
    @media (max-width: 768px) {
      .logo-img {
        width: 100px;
      }
      .name {
        height: 128px;
        .bg {
          font-size: 4.5rem;
        }
      }
    }

    @media (max-width: 720px) {
      max-width: 100%;
    }
  }

  .description {
    position: relative;
    padding: 1rem;
    margin-top: 3.5rem;
    max-width: 460px;
    animation: fade 0.5s;

    .content {
      display: flex;
      justify-content: space-between;

      .text {
        margin: 0.75rem 1rem;
        line-height: 2rem;
        margin-right: auto;
        transition: opacity 0.2s;

        p {
          &:nth-of-type(1) {
            font-family: "Pacifico-Regular";
          }
        }
      }

      .quote-flip {
        transform: scaleX(-1);
      }

      .xicon:nth-of-type(2) {
        align-self: flex-end;
      }
    }

    .site-count {
      position: absolute;
      right: 12px;
      bottom: 6px;
      display: flex;
      align-items: center;
      gap: 3px;
      font-size: 0.7rem;
      opacity: 0.5;
      pointer-events: none;
    }

    @media (max-width: 720px) {
      max-width: 100%;
    }
  }
}
</style>

// next-app/src/components/message.tsx
"use client";

import { motion, AnimatePresence } from "framer-motion";
import { Eye, Quote, Users } from "lucide-react";
import { useMemo } from "react";
import { siteConfig } from "@/lib/config";
import { useMain } from "@/store/main";
import { useBusuanzi } from "@/hooks/use-busuanzi";
import { Card } from "@/components/ui/card";

function parseUrl(raw: string): [string, string] {
  const url = raw || "saop.cc";
  const clean = url.replace(/^(https?:\/\/)/, "");
  const parts = clean.split(".");
  return [parts[0] ?? "saop", parts.slice(1).join(".") || "cc"];
}

export function Message() {
  const [namePart, tldPart] = useMemo(() => parseUrl(siteConfig.siteUrl), []);
  const boxOpen = useMain((s) => s.boxOpenState);
  const setStore = useMain((s) => s.set);
  const stats = useBusuanzi();

  const hello = boxOpen ? siteConfig.descHelloOther : siteConfig.descHello;
  const text = boxOpen ? siteConfig.descTextOther : siteConfig.descText;
  const isLong = namePart.length >= 6;

  return (
    <div className="animate-fade-in">
      <div className="flex items-center max-w-[460px]">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={siteConfig.siteMainLogo} alt="logo" className="h-[120px] w-[120px] rounded-full md:h-[120px] sm:h-[100px] sm:w-[100px]" />
        <div className="pl-6 -translate-y-2 font-pacifico truncate">
          <span className={isLong ? "text-5xl sm:text-4xl" : "text-[5rem] sm:text-[4.5rem]"}>{namePart}</span>
          <span className="ml-1.5 text-3xl sm:text-2xl">.{tldPart}</span>
        </div>
      </div>

      <Card
        onClick={() => setStore("boxOpenState", !boxOpen)}
        className="relative mt-14 max-w-[460px] p-4 cursor-pointer animate-fade-in glass-hover"
      >
        <div className="flex justify-between">
          <Quote size={16} className="shrink-0" />
          <AnimatePresence mode="wait">
            <motion.div
              key={hello + text}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="mx-4 my-2 leading-8 mr-auto"
            >
              <p className="font-pacifico">{hello}</p>
              <p>{text}</p>
            </motion.div>
          </AnimatePresence>
          <Quote size={16} className="shrink-0 -scale-x-100 self-end" />
        </div>
        {stats && (
          <div className="absolute right-3 bottom-1.5 flex items-center gap-1 text-[0.7rem] opacity-60 pointer-events-none">
            <Eye size={12} />
            <span>{stats.pv}</span>
            <Users size={12} />
            <span>{stats.uv}</span>
          </div>
        )}
      </Card>
    </div>
  );
}
