// app/components/MusicPanel.vue
<template>
  <!-- 音乐控制面板 -->
  <div
    v-show="store.musicOpenState"
    class="music"
    @mouseenter="volumeShow = true"
    @mouseleave="volumeShow = false"
  >
    <!-- 移动端顶部按钮栏 -->
    <div v-if="isMobile" class="mobile-top-bar">
      <span @click="openMusicList()">音乐列表</span>
      <span @click="toggleVolume">{{ mobileVolumeShow ? '隐藏音量' : '调节音量' }}</span>
      <span @click="store.musicOpenState = false">回到一言</span>
    </div>
    <div v-if="!isMobile" class="btns">
      <span @click="openMusicList()">音乐列表</span>
      <span @click="store.musicOpenState = false">回到一言</span>
    </div>
    <div class="control">
      <SkipBack :size="30" color="#efefef" fill="#efefef" @click="changeMusicIndex(0)" />
      <Transition name="fade" mode="out-in">
        <div :key="String(store.playerState)" class="state" @click="changePlayState">
          <Play v-show="!store.playerState" :size="50" color="#efefef" fill="#efefef" />
          <Pause v-show="store.playerState" :size="50" color="#efefef" fill="#efefef" />
        </div>
      </Transition>
      <SkipForward :size="30" color="#efefef" fill="#efefef" @click="changeMusicIndex(1)" />
    </div>
    <div class="menu">
      <div v-show="isMobile ? !mobileVolumeShow : !volumeShow" class="name">
        <span>{{
          store.getPlayerData.name
            ? store.getPlayerData.name + " - " + store.getPlayerData.artist
            : "未播放音乐"
        }}</span>
      </div>
      <div v-show="isMobile ? mobileVolumeShow : volumeShow" class="volume">
        <div class="icon">
          <VolumeX v-if="volumeNum === 0" :size="24" color="#efefef" />
          <Volume1 v-else-if="volumeNum > 0 && volumeNum < 0.7" :size="24" color="#efefef" />
          <Volume2 v-else :size="24" color="#efefef" />
        </div>
        <el-slider v-model="volumeNum" :show-tooltip="false" :min="0" :max="1" :step="0.01" />
      </div>
    </div>
  </div>
  <!-- 音乐列表弹窗 -->
  <Transition name="fade" mode="out-in">
    <div v-show="musicListShow" class="music-list" @click="closeMusicList()">
      <Transition name="zoom">
        <div v-show="musicListShow" class="list" @click.stop>
          <CircleX
            class="close"
            :size="28"
            color="#ffffff60"
            @click="closeMusicList()"
          />
          <MusicPlayer
            ref="playerRef"
            :song-server="playerData.server"
            :song-type="playerData.type"
            :song-id="playerData.id"
            :volume="volumeNum"
          />
        </div>
      </Transition>
    </div>
  </Transition>
</template>

<script setup lang="ts">
import { SkipBack, Play, Pause, SkipForward, CircleX, VolumeX, Volume1, Volume2 } from "lucide-vue-next";

const store = mainStore();
const config = useRuntimeConfig();

const isMobile = computed(() => store.innerWidth !== null && store.innerWidth < 721);

// 音量条数据
const volumeShow = ref(false);
const mobileVolumeShow = ref(false);
const volumeNum = ref(store.musicVolume ? store.musicVolume : 0.7);

function toggleVolume() {
  mobileVolumeShow.value = !mobileVolumeShow.value;
}

// 播放列表数据
const musicListShow = ref(false);
const playerRef = ref<{ toggleList: () => void; playToggle: () => void; changeSong: (type: number) => void; changeVolume: (value: number) => void } | null>(null);
const playerData = reactive({
  server: config.public.songServer,
  type: config.public.songType,
  id: String(config.public.songId),
});

// 开启播放列表
const openMusicList = () => {
  musicListShow.value = true;
  playerRef.value?.toggleList();
};

// 关闭播放列表
const closeMusicList = () => {
  musicListShow.value = false;
  playerRef.value?.toggleList();
};

// 音乐播放暂停
const changePlayState = () => {
  playerRef.value?.playToggle();
};

// 音乐上下曲
const changeMusicIndex = (type: number) => {
  playerRef.value?.changeSong(type);
};

onMounted(() => {
  window.addEventListener("keydown", (e) => {
    if (!store.musicIsOk) {
      return;
    }
    if (e.code === "Space") {
      changePlayState();
    }
  });
  window.$openList = openMusicList as () => void;
});

// 监听音量变化
watch(
  () => volumeNum.value,
  (value) => {
    store.musicVolume = value;
    playerRef.value?.changeVolume(store.musicVolume);
  },
);
</script>

<style lang="scss" scoped>
.music {
  width: 100%;
  height: 100%;
  background: #00000040;
  backdrop-filter: blur(10px);
  border-radius: 6px;
  padding: 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-direction: column;
  animation: fade 0.5s;
  .mobile-top-bar {
    display: flex;
    align-items: center;
    gap: 6px;
    margin-bottom: 6px;
    span {
      background: #ffffff26;
      padding: 4px 10px;
      border-radius: 6px;
      font-size: 0.8rem;
      white-space: nowrap;
      &:active {
        background: #ffffff4d;
      }
    }
  }
  .btns {
    display: flex;
    align-items: center;
    margin-bottom: 6px;
    span {
      background: #ffffff26;
      padding: 2px 8px;
      border-radius: 6px;
      margin: 0px 6px;
      text-overflow: ellipsis;
      overflow-x: hidden;
      white-space: nowrap;
      &:hover {
        background: #ffffff4d;
      }
    }
  }
  .control {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-evenly;
    width: 100%;
    .state {
      transition: opacity 0.1s;
      .i-icon {
        width: 50px;
        height: 50px;
        display: block;
      }
    }
    .i-icon {
      width: 36px;
      height: 36px;
      display: flex;
      border-radius: 6px;
      align-items: center;
      justify-content: center;
      border-radius: 6px;
      transform: scale(1);
      &:hover {
        background: #ffffff33;
      }
      &:active {
        transform: scale(0.95);
      }
    }
  }
  .menu {
    height: 26px;
    width: 100%;
    line-height: 26px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    .name {
      width: 100%;
      text-align: center;
      text-overflow: ellipsis;
      overflow-x: hidden;
      white-space: nowrap;
      animation: fade 0.3s;
    }
    .volume {
      width: 100%;
      padding: 0 12px;
      display: flex;
      align-items: center;
      flex-direction: row;
      animation: fade 0.3s;
      .icon {
        margin-right: 12px;
        span {
          width: 24px;
          height: 24px;
          display: block;
        }
      }
      :deep(*) {
        transition: none;
      }
      :deep(.el-slider__button) {
        transition: 0.3s;
      }
      .el-slider {
        margin-right: 12px;
        --el-slider-main-bg-color: #efefef;
        --el-slider-runway-bg-color: #ffffff40;
        --el-slider-button-size: 16px;
      }
    }
  }
}
.music-list {
  position: fixed;
  top: 0;
  left: 0;
  margin: auto;
  width: 100%;
  height: 100%;
  background-color: #00000080;
  backdrop-filter: blur(20px);
  z-index: 1;
  .list {
    position: absolute;
    display: flex;
    align-items: center;
    justify-content: center;
    top: calc(50% - 300px);
    left: calc(50% - 320px);
    width: 640px;
    height: 600px;
    background-color: #ffffff66;
    border-radius: 6px;
    z-index: 999;
    @media (max-width: 720px) {
      left: calc(50% - 45%);
      width: 90%;
    }
    .close {
      position: absolute;
      top: 12px;
      right: 12px;
      width: 28px;
      height: 28px;
      display: block;
      &:hover {
        transform: scale(1.2);
      }
      &:active {
        transform: scale(0.95);
      }
    }
  }
}

.zoom-enter-active {
  animation: zoom 0.4s ease-in-out;
}
.zoom-leave-active {
  animation: zoom 0.3s ease-in-out reverse;
}
@keyframes zoom {
  0% {
    opacity: 0;
    transform: scale(0) translateY(-600px);
  }
  100% {
    opacity: 1;
    transform: scale(1) translateY(0);
  }
}
</style>

// next-app/src/components/music-panel.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Pause, Play, SkipBack, SkipForward, Volume1, Volume2, VolumeX } from "lucide-react";
import { siteConfig } from "@/lib/config";
import { useMain } from "@/store/main";
import { useIsMobile } from "@/hooks/use-mobile";
import { Slider } from "@/components/ui/slider";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { MusicEngine, PlaylistView, type PlayerHandle } from "./music-player";

declare global {
  interface Window { $openList?: () => void }
}

export function MusicPanel() {
  const musicOpenState = useMain((s) => s.musicOpenState);
  const playerState = useMain((s) => s.playerState);
  const playerTitle = useMain((s) => s.playerTitle);
  const playerArtist = useMain((s) => s.playerArtist);
  const musicVolume = useMain((s) => s.musicVolume);
  const setStore = useMain((s) => s.set);
  const isMobile = useIsMobile();

  const playerRef = useRef<PlayerHandle | null>(null);
  const [desktopVol, setDesktopVol] = useState(false);
  const [mobileVol, setMobileVol] = useState(false);
  const [listOpen, setListOpen] = useState(false);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (!useMain.getState().musicIsOk) return;
      if (e.code === "Space" && document.activeElement?.tagName !== "INPUT") {
        e.preventDefault();
        playerRef.current?.toggle();
      }
    };
    window.addEventListener("keydown", onKey);
    window.$openList = () => setListOpen(true);
    return () => {
      window.removeEventListener("keydown", onKey);
      window.$openList = undefined;
    };
  }, []);

  const volShowing = isMobile ? mobileVol : desktopVol;

  return (
    <>
      {/* headless engine: single mount, never unmounts */}
      <MusicEngine
        ref={playerRef}
        server={siteConfig.songServer}
        type={siteConfig.songType}
        id={siteConfig.songId}
      />

      <AnimatePresence>
        {musicOpenState && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onMouseEnter={() => setDesktopVol(true)}
            onMouseLeave={() => setDesktopVol(false)}
            className="h-full w-full rounded-2xl bg-black/40 backdrop-blur-md p-5 flex flex-col justify-between items-center text-white"
          >
            <div className="flex items-center gap-1.5 mb-1.5 flex-wrap justify-center">
              <Chip onClick={() => setListOpen(true)}>音乐列表</Chip>
              {isMobile && (
                <Chip onClick={() => setMobileVol((v) => !v)}>{mobileVol ? "隐藏音量" : "调节音量"}</Chip>
              )}
              <Chip onClick={() => setStore("musicOpenState", false)}>回到一言</Chip>
            </div>
            <div className="flex flex-row items-center justify-evenly w-full">
              <button onClick={() => playerRef.current?.prev()} className="p-2 rounded-md hover:bg-white/20 active:scale-95 transition-transform">
                <SkipBack size={28} className="fill-white text-white" />
              </button>
              <AnimatePresence mode="wait">
                <motion.button
                  key={String(playerState)}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 0.1 }}
                  onClick={() => playerRef.current?.toggle()}
                  className="p-2 rounded-md hover:bg-white/20 active:scale-95 transition-transform"
                >
                  {playerState ? <Pause size={48} className="fill-white text-white" /> : <Play size={48} className="fill-white text-white" />}
                </motion.button>
              </AnimatePresence>
              <button onClick={() => playerRef.current?.next()} className="p-2 rounded-md hover:bg-white/20 active:scale-95 transition-transform">
                <SkipForward size={28} className="fill-white text-white" />
              </button>
            </div>
            <div className="h-6 w-full flex items-center justify-center">
              {!volShowing ? (
                <div className="w-full text-center truncate animate-fade-in">
                  {playerTitle ? `${playerTitle} - ${playerArtist}` : "未播放音乐"}
                </div>
              ) : (
                <div className="w-full px-3 flex items-center gap-3 animate-fade-in">
                  <div className="shrink-0">
                    {musicVolume === 0 ? <VolumeX size={20} /> : musicVolume < 0.7 ? <Volume1 size={20} /> : <Volume2 size={20} />}
                  </div>
                  <Slider
                    value={[musicVolume]}
                    min={0} max={1} step={0.01}
                    onValueChange={(v) => playerRef.current?.setVolume(v[0] ?? 0)}
                  />
                </div>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <Dialog open={listOpen} onOpenChange={setListOpen}>
        <DialogContent className="max-w-xl h-[70vh] p-4 flex flex-col">
          <div className="flex-1 min-h-0">
            <PlaylistView onSelect={(i) => playerRef.current?.playAt(i)} />
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

function Chip({ children, onClick }: { children: React.ReactNode; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      className="bg-white/20 hover:bg-white/30 active:bg-white/40 px-2.5 py-1 rounded-md text-sm whitespace-nowrap"
    >
      {children}
    </button>
  );
}
