// src/components/TimeCapsule.vue
<template>
  <div class="time-capsule">
    <div class="title">
      <Hourglass :size="24" color="#efefef" />
      <span>时光胶囊</span>
    </div>
    <div v-if="timeData" class="all-capsule">
      <div v-for="(item, tag, index) in timeData" :key="index" class="capsule-item">
        <div class="item-title">
          <span class="percentage">
            {{ item.name }}已度过
            <strong>{{ item.passed }}</strong>
            {{ tag === "day" ? "小时" : "天" }}
          </span>
          <span class="remaining">
            剩余&nbsp;{{ item.remaining }}&nbsp;{{ tag === "day" ? "小时" : "天" }}
          </span>
        </div>
        <el-progress :text-inside="true" :stroke-width="20" :percentage="parseFloat(item.percentage)" />
      </div>
      <!-- 建站日期 -->
      <div v-if="store.siteStartShow" class="capsule-item start">
        <div class="item-title">{{ startDateText }}</div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { Hourglass } from "lucide-vue-next";
import { getTimeCapsule, siteDateStatistics } from "@/utils/getTime.js";
import { mainStore } from "@/store";
const store = mainStore();

// 进度条数据
const timeData = ref(getTimeCapsule());
const startDate = ref(import.meta.env.VITE_SITE_START);
const startDateText = ref(null);
const timeInterval = ref(null);

onMounted(() => {
  timeInterval.value = setInterval(() => {
    timeData.value = getTimeCapsule();
    if (startDate.value) startDateText.value = siteDateStatistics(new Date(startDate.value));
  }, 1000);
});

onBeforeUnmount(() => {
  clearInterval(timeInterval.value);
});
</script>

<style lang="scss" scoped>
.time-capsule {
  width: 100%;
  .title {
    display: flex;
    flex-direction: row;
    align-items: center;
    margin: 0.2rem 0 1.5rem;
    font-size: 1.1rem;
    .i-icon {
      display: flex;
      justify-content: center;
      align-items: center;
      margin-right: 6px;
    }
  }
  .all-capsule {
    .capsule-item {
      margin-bottom: 1rem;
      .item-title {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        margin: 1rem 0rem 0.5rem 0rem;
        font-size: 0.95rem;
        .remaining {
          opacity: 0.6;
          font-size: 0.85rem;
          font-style: oblique;
        }
      }
      &:last-child {
        margin-bottom: 0;
      }
      &.start {
        .item-title {
          justify-content: center;
          opacity: 0.8;
          font-size: 0.85rem;
        }
      }
    }
  }
}
</style>

// next-app/src/components/time-capsule.tsx
"use client";

import { useEffect, useState } from "react";
import { Hourglass } from "lucide-react";
import { getTimeCapsule, siteDateStatistics, type TimeCapsule as TC } from "@/lib/get-time";
import { siteConfig } from "@/lib/config";
import { useMain } from "@/store/main";
import { Progress } from "@/components/ui/progress";

export function TimeCapsule() {
  const siteStartShow = useMain((s) => s.siteStartShow);
  const [data, setData] = useState<TC>(() => getTimeCapsule());
  const [startText, setStartText] = useState<string | null>(null);

  useEffect(() => {
    const startDate = siteConfig.siteStart ? new Date(siteConfig.siteStart) : null;
    const tick = () => {
      setData(getTimeCapsule());
      if (startDate) setStartText(siteDateStatistics(startDate));
    };
    tick();
    const id = setInterval(tick, 1000);
    return () => clearInterval(id);
  }, []);

  const entries = [
    ["day", data.day] as const,
    ["week", data.week] as const,
    ["month", data.month] as const,
    ["year", data.year] as const,
  ];

  return (
    <div className="w-full">
      <div className="flex items-center mb-6 text-[1.1rem]">
        <Hourglass size={24} className="mr-1.5" />
        <span>时光胶囊</span>
      </div>
      <div>
        {entries.map(([tag, item]) => {
          const unit = tag === "day" ? "小时" : "天";
          return (
            <div key={tag} className="mb-4 last:mb-0">
              <div className="flex items-center justify-between mt-2 mb-2 text-sm">
                <span>
                  {item.name}已度过 <strong>{item.passed}</strong> {unit}
                </span>
                <span className="opacity-60 text-xs italic">剩余 {item.remaining} {unit}</span>
              </div>
              <Progress value={parseFloat(item.percentage)} label={`${item.percentage}%`} />
            </div>
          );
        })}
        {siteStartShow && startText && (
          <div className="mt-2 text-center opacity-80 text-xs">{startText}</div>
        )}
      </div>
    </div>
  );
}
