// next-app/src/components/app-background.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { toast } from "sonner";
import { CircleAlert } from "lucide-react";
import { siteConfig } from "@/lib/config";
import { useMain } from "@/store/main";

const BG_SOURCES: Record<string, () => string> = {
  "0": () => "", // default; replaced below
  "1": () => siteConfig.bgBingUrl || "https://api.paugram.com/bing/",
  "2": () => siteConfig.bgSceneryUrl || "https://api.dujin.org/bing/1920.php",
  "3": () => siteConfig.bgAnimeUrl || "https://t.mwm.moe/fj/",
};

export function AppBackground({ onLoadComplete }: { onLoadComplete?: () => void }) {
  const coverType = useMain((s) => s.coverType);
  const backgroundShow = useMain((s) => s.backgroundShow);
  const imgLoaded = useMain((s) => s.imgLoadStatus);
  const setStore = useMain((s) => s.set);

  const [bgUrl, setBgUrl] = useState<string>("");
  const fallbackRef = useRef(false);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const localIdx = useRef(Math.floor(Math.random() * siteConfig.bgLocalCount) + 1);
  const getLocal = () => `/images/background${localIdx.current}.jpg`;

  useEffect(() => {
    fallbackRef.current = false;
    if (timerRef.current) clearTimeout(timerRef.current);
    setStore("imgLoadStatus", false);

    const get = BG_SOURCES[coverType];
    const url = coverType === "0" ? getLocal() : get ? get() : getLocal();
    setBgUrl(url);

    if (coverType !== "0") {
      timerRef.current = setTimeout(() => {
        if (!useMain.getState().imgLoadStatus) {
          console.warn("壁纸加载超时，切换至本地");
          fallbackRef.current = true;
          setBgUrl(getLocal());
        }
      }, 8000);
    }

    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [coverType]);

  const onImgLoad = () => {
    if (timerRef.current) clearTimeout(timerRef.current);
    setStore("imgLoadStatus", true);
  };

  const onImgError = () => {
    if (timerRef.current) clearTimeout(timerRef.current);
    if (fallbackRef.current) {
      setStore("imgLoadStatus", true);
      onLoadComplete?.();
      return;
    }
    toast("壁纸加载失败，已切换回默认", { icon: <CircleAlert size={18} /> });
    fallbackRef.current = true;
    setBgUrl(getLocal());
  };

  return (
    <div className={`absolute inset-0 transition-all duration-300 ${backgroundShow ? "z-[1]" : "z-[-1]"}`}>
      {bgUrl && (
        /* eslint-disable-next-line @next/next/no-img-element */
        <img
          src={bgUrl}
          alt="cover"
          onLoad={onImgLoad}
          onError={onImgError}
          onAnimationEnd={() => onLoadComplete?.()}
          fetchPriority="high"
          decoding="async"
          className={`absolute inset-0 h-full w-full object-cover backface-hidden ${imgLoaded ? "animate-fade-blur-in" : "opacity-0"}`}
          style={{ filter: "blur(0) brightness(1)" }}
        />
      )}
      <div
        className="absolute inset-0 transition-opacity duration-[1500ms]"
        style={{
          opacity: backgroundShow ? 0 : 1,
          backgroundImage:
            "radial-gradient(rgba(0,0,0,0) 0, rgba(0,0,0,0.5) 100%), radial-gradient(rgba(0,0,0,0) 33%, rgba(0,0,0,0.3) 166%)",
        }}
      />
      <AnimatePresence>
        {backgroundShow && coverType !== "3" && (
          <motion.a
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            href={bgUrl}
            target="_blank"
            rel="noreferrer"
            className="absolute bottom-8 left-1/2 -translate-x-1/2 text-white px-6 py-4 rounded-lg bg-black/30 hover:bg-black/60 hover:scale-105 transition-transform"
          >
            下载壁纸
          </motion.a>
        )}
      </AnimatePresence>
    </div>
  );
}

// components/AppBackground.vue
<template>
  <div :class="store.backgroundShow ? 'cover show' : 'cover'">
    <img
      v-show="store.imgLoadStatus" :src="bgUrl" class="bg" alt="cover" @load="imgLoadComplete"
      @error.once="imgLoadError" @animationend="imgAnimationEnd"
    />
    <div :class="store.backgroundShow ? 'gray hidden' : 'gray'"></div>
    <Transition name="fade" mode="out-in">
      <a v-if="store.backgroundShow && store.coverType !== '3'" class="down" :href="bgUrl" target="_blank">
        下载壁纸
      </a>
    </Transition>
  </div>
</template>

<script setup lang="ts">
import { CircleAlert } from "lucide-vue-next";

const emit = defineEmits(["loadComplete"]);
const store = mainStore();
const config = useRuntimeConfig();
const bgUrl = ref(null);
const imgTimeout = ref(null);
// 壁纸随机数
const bgLocalCount = Number(config.public.bgLocalCount) || 10;
const bgRandom = Math.floor(Math.random() * bgLocalCount + 1);

// 壁纸源配置 (可通过 .env 自定义 URL)
const BG_SOURCES = {
  0: () => `/images/background${bgRandom}.jpg`,
  1: () => config.public.bgBingUrl || "https://api.paugram.com/bing/",
  2: () => config.public.bgSceneryUrl || "https://api.fw1028.top/scenery.php?return=img",
  3: () => config.public.bgAnimeUrl || "https://www.loliapi.com/acg/",
};

// 更换壁纸链接
const changeBg = (type) => {
  const getUrl = BG_SOURCES[type];
  if (getUrl) bgUrl.value = getUrl();
};

// 图片加载完成
const imgLoadComplete = () => {
  imgTimeout.value = setTimeout(
    () => {
      store.setImgLoadStatus(true);
    },
    Math.floor(Math.random() * (600 - 300 + 1)) + 300,
  );
};

// 图片动画完成
const imgAnimationEnd = () => {
  console.log("壁纸加载且动画完成");
  emit("loadComplete");
};

// 图片显示失败
const imgLoadError = () => {
  console.error("壁纸加载失败：", bgUrl.value);
  ElMessage({
    message: "壁纸加载失败，已临时切换回默认",
    icon: h(CircleAlert, { size: 20, color: "#efefef" }),
  });
  bgUrl.value = `/images/background${bgRandom}.jpg`;
};

// 监听壁纸切换
watch(
  () => store.coverType,
  (value) => {
    changeBg(value);
  },
);

onMounted(() => {
  changeBg(store.coverType);
});

onBeforeUnmount(() => {
  clearTimeout(imgTimeout.value);
});
</script>

<style lang="scss" scoped>
.cover {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  transition: 0.25s;
  z-index: -1;

  &.show {
    z-index: 1;
  }

  .bg {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
    backface-visibility: hidden;
    filter: blur(20px) brightness(0.3);
    transition:
      filter 0.3s,
      transform 0.3s;
    animation: fade-blur-in 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards;
    animation-delay: 0.45s;
  }

  .gray {
    opacity: 1;
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background-image: radial-gradient(rgba(0, 0, 0, 0) 0, rgba(0, 0, 0, 0.5) 100%),
      radial-gradient(rgba(0, 0, 0, 0) 33%, rgba(0, 0, 0, 0.3) 166%);

    transition: 1.5s;

    &.hidden {
      opacity: 0;
      transition: 1.5s;
    }
  }

  .down {
    font-size: 16px;
    color: white;
    position: absolute;
    bottom: 30px;
    left: 0;
    right: 0;
    margin: 0 auto;
    display: flex;
    padding: 20px 26px;
    border-radius: 8px;
    background-color: #00000030;
    width: 120px;
    height: 30px;
    justify-content: center;
    align-items: center;

    &:hover {
      transform: scale(1.05);
      background-color: #00000060;
    }

    &:active {
      transform: scale(1);
    }
  }
}
</style>
