// next-app/src/components/box-panel.tsx
"use client";

import { useState } from "react";
import { Settings, X } from "lucide-react";
import { useMain } from "@/store/main";
import { useIsMobile } from "@/hooks/use-mobile";
import { Card } from "@/components/ui/card";
import { TimeCapsule } from "./time-capsule";
import { MoreContent } from "./more-content";

export function BoxPanel({ className = "" }: { className?: string }) {
  const setStore = useMain((s) => s.set);
  const [hover, setHover] = useState(false);
  const isMobile = useIsMobile();
  const show = hover || isMobile;

  return (
    <Card
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      className={`relative flex-1 h-[80%] max-w-[50%] ml-3 animate-fade-in ${className}`}
    >
      {show && (
        <>
          <button
            onClick={() => setStore("boxOpenState", false)}
            className="focus-ring absolute top-3.5 right-3.5 text-white/60 hover:text-white hover:scale-110 active:scale-100 transition-all p-1"
            aria-label="关闭"
          >
            <X size={28} />
          </button>
          <button
            onClick={() => {
              setStore("boxOpenState", false);
              setStore("setOpenState", true);
            }}
            className="focus-ring absolute top-3.5 right-14 text-white/60 hover:text-white hover:scale-110 active:scale-100 transition-all p-1"
            aria-label="设置"
          >
            <Settings size={28} />
          </button>
        </>
      )}
      <div className="flex flex-col p-8 sm:p-4 sm:pt-12 w-full h-full overflow-y-auto">
        <TimeCapsule />
        <MoreContent />
      </div>
    </Card>
  );
}

// components/BoxPanel.vue
<template>
  <div class="box cards" @mouseenter="closeShow = true" @mouseleave="closeShow = false">
    <transition name="el-fade-in-linear">
      <CircleX
        v-show="closeShow"
        class="close"
        :size="28"
        color="#ffffff60"
        @click="store.boxOpenState = false"
      />
    </transition>
    <transition name="el-fade-in-linear">
      <Settings
        v-show="closeShow"
        class="setting"
        :size="28"
        color="#ffffff60"
        @click="store.setOpenState = true"
      />
    </transition>
    <div class="content">
      <!-- 可在此处自定义任意内容 -->
      <TimeCapsule />
      <MoreContent />
    </div>
  </div>
</template>

<script setup lang="ts">
import { CircleX, Settings } from "lucide-vue-next";

const store = mainStore();
const closeShow = ref(false);
</script>

<style lang="scss" scoped>
.box {
  flex: 1 0 0%;
  margin-left: 0.75rem;
  height: 80%;
  max-width: 50%;
  position: relative;
  animation: fade 0.5s;

  &:hover {
    transform: scale(1);
  }

  .close,
  .setting {
    position: absolute;
    top: 14px;
    right: 14px;
    width: 28px;
    height: 28px;
    transition:
      transform 0.3s,
      opacity 0.3s;

    &:hover {
      transform: scale(1.2);
    }

    &:active {
      transform: scale(1);
    }
  }

  .setting {
    right: 56px;
  }

  .content {
    display: flex;
    flex-direction: column;
    padding: 30px;
    width: 100%;
    height: 100%;
  }
}
</style>
