// app/components/AppFooter.vue
<template>
  <footer id="footer" :class="store.footerBlur ? 'blur' : null">
    <Transition name="fade" mode="out-in">
      <div v-if="!store.playerState || !store.playerLrcShow" class="power">
        <span>
          <span :class="startYear !== null && startYear < fullYear ? 'c-hidden' : 'hidden'">Copyright&nbsp;</span>
          &copy;
          <span v-if="startYear !== null && startYear < fullYear" class="site-start">
            {{ startYear }}
            -
          </span>
          {{ fullYear }}
          <a :href="siteUrl">{{ config.public.siteAuthor }}</a>
        </span>
        <!-- 站点备案 -->
        <span>
          &amp;
          <a v-if="config.public.siteIcp" :href="config.public.siteIcpUrl || 'https://beian.miit.gov.cn'" target="_blank">
            {{ config.public.siteIcp }}
          </a>
        </span>
      </div>
      <div v-else class="lrc">
        <Transition name="fade" mode="out-in">
          <div :key="store.playerLrc" class="lrc-all">
            <Music :size="18" color="#efefef" />
            <span class="lrc-text text-hidden" v-html="store.playerLrc"/>
            <Music :size="18" color="#efefef" />
          </div>
        </Transition>
      </div>
    </Transition>
  </footer>
</template>

<script setup lang="ts">
import { Music } from "lucide-vue-next";

const store = mainStore();
const config = useRuntimeConfig();
const fullYear = new Date().getFullYear();

// 加载配置数据
const startYear = ref<number | null>(
  config.public.siteStart?.length >= 4
    ? Number(config.public.siteStart.substring(0, 4))
    : null,
);

const siteUrl = computed(() => {
  const url = config.public.siteUrl;
  if (!url) return "https://saop.cc";
  if (!url.startsWith("http://") && !url.startsWith("https://")) {
    return `//${  url}`;
  }
  return url;
});
</script>

<style lang="scss" scoped>
#footer {
  width: 100%;
  position: absolute;
  bottom: 0;
  left: 0;
  height: 46px;
  line-height: 46px;
  text-align: center;
  z-index: 0;
  font-size: 14px;
  word-break: keep-all;
  white-space: nowrap;
  .power {
    animation: fade 0.3s;
  }
  .lrc {
    padding: 0 20px;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    .lrc-all {
      width: 98%;
      display: flex;
      flex-direction: row;
      justify-content: center;
      align-items: center;
      .lrc-text {
        margin: 0 8px;
      }
      .i-icon {
        width: 18px;
        height: 18px;
        display: inherit;
      }
    }
  }
  &.blur {
    backdrop-filter: blur(10px);
    background: rgb(0 0 0 / 25%);
    font-size: 16px;
  }
  .fade-enter-active,
  .fade-leave-active {
    transition: opacity 0.15s ease-in-out;
  }
  @media (max-width: 720px) {
    bottom: 60px;
    font-size: 0.9rem;
    &.blur {
      font-size: 0.9rem;
    }
  }
  @media (max-width: 560px) {
    .c-hidden {
      display: none;
    }
  }
  @media (max-width: 480px) {
    .hidden {
      display: none;
    }
  }
}
</style>

// src/components/app-footer.tsx
"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Music } from "lucide-react";
import { siteConfig } from "@/lib/config";
import { useMain } from "@/store/main";

export function AppFooter() {
  const blur = useMain((s) => s.footerBlur);
  const lrcShow = useMain((s) => s.playerLrcShow);
  const playing = useMain((s) => s.playerState);
  const lrc = useMain((s) => s.playerLrc);

  const fullYear = new Date().getFullYear();
  const startYear = siteConfig.siteStart?.length >= 4 ? Number(siteConfig.siteStart.substring(0, 4)) : null;
  const siteUrl = siteConfig.siteUrl?.startsWith("http") ? siteConfig.siteUrl : `//${siteConfig.siteUrl}`;
  const showLrc = playing && lrcShow;

  return (
    <footer
      className={`absolute bottom-0 left-0 w-full h-[46px] leading-[46px] text-center z-0 text-sm whitespace-nowrap sm:bottom-[60px] ${blur ? "backdrop-blur-md bg-black/25 text-base" : ""}`}
    >
      <AnimatePresence mode="wait">
        {showLrc ? (
          <motion.div
            key="lrc"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
            className="px-5 flex items-center justify-center"
          >
            <div className="flex items-center justify-center w-[98%]">
              <Music size={18} />
              <AnimatePresence mode="wait">
                <motion.span
                  key={lrc}
                  initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                  className="mx-2 truncate"
                >
                  {lrc}
                </motion.span>
              </AnimatePresence>
              <Music size={18} />
            </div>
          </motion.div>
        ) : (
          <motion.div
            key="power"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
          >
            <span>
              <span className="hidden sm:inline">Copyright&nbsp;</span>
              ©
              {startYear !== null && startYear < fullYear && <span>{startYear} - </span>}
              {fullYear}{" "}
              <a
                href={siteUrl}
                className="focus-ring underline-offset-4 hover:underline hover:text-white/90 transition-colors"
              >
                {siteConfig.siteAuthor}
              </a>
            </span>
            {siteConfig.siteIcp && (
              <span>
                &nbsp;&amp;&nbsp;
                <a
                  href={siteConfig.siteIcpUrl || "https://beian.miit.gov.cn"}
                  target="_blank"
                  rel="noreferrer"
                  className="focus-ring underline-offset-4 hover:underline hover:text-white/90 transition-colors"
                >
                  {siteConfig.siteIcp}
                </a>
              </span>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </footer>
  );
}
