// app/components/MoreContent.vue
<template>
  <div class="more-content">
    <div class="action-btn cards" @click="store.commentOpenState = true">
      <MessageSquare :size="20" />
      <span>留言板</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { MessageSquare } from "lucide-vue-next";

const store = mainStore();
</script>

<style lang="scss" scoped>
.more-content {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 20px;
  width: 100%;
  height: 100%;
  .action-btn {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 10px 24px;
    font-size: 0.95rem;
    cursor: pointer;
    transition:
      transform 0.3s,
      background-color 0.3s;
    &:hover {
      background-color: #ffffff20;
      transform: scale(1.05);
    }
    &:active {
      transform: scale(0.97);
    }
  }
}
</style>

// src/components/more-content.tsx
"use client";

import { MessageSquare } from "lucide-react";
import { useMain } from "@/store/main";
import { Card } from "@/components/ui/card";

export function MoreContent() {
  const setStore = useMain((s) => s.set);
  return (
    <div className="mt-5 flex items-center justify-center w-full">
      <Card
        onClick={() => setStore("commentOpenState", true)}
        className="flex items-center gap-2 px-6 py-2.5 cursor-pointer transition-all hover:bg-white/20 hover:scale-105 active:scale-[0.97]"
      >
        <MessageSquare size={20} />
        <span className="text-[0.95rem]">留言板</span>
      </Card>
    </div>
  );
}
