// components/SocialLinks.vue
<template>
  <!-- 社交链接 -->
  <div class="social">
    <div class="link">
      <a
        v-for="item in socialLinks"
        :key="item.name"
        :href="item.url"
        target="_blank"
        @mouseenter="socialTip = item.tip"
        @mouseleave="socialTip = '通过这里联系我吧'"
      >
        <img class="icon" :src="item.icon" height="24" />
      </a>
    </div>
    <span class="tip">{{ socialTip }}</span>
  </div>
</template>

<script setup lang="ts">
import socialLinks from "~/assets/socialLinks.json";

// 社交链接提示
const socialTip = ref("通过这里联系我吧");
</script>

<style lang="scss" scoped>
.social {
  margin-top: 1rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
  max-width: 460px;
  width: 100%;
  height: 42px;
  background-color: transparent;
  border-radius: 6px;
  backdrop-filter: blur(0);
  animation: fade 0.5s;
  transition:
    background-color 0.3s,
    backdrop-filter 0.3s;
  @media (max-width: 840px) {
    max-width: 100%;
    justify-content: center;
    .link {
      justify-content: space-evenly !important;
      width: 90%;
    }
    .tip {
      display: none !important;
    }
  }

  .link {
    display: flex;
    align-items: center;
    justify-content: center;
    a {
      display: inherit;
      .icon {
        margin: 0 12px;
        transition: transform 0.3s;
        &:hover {
          transform: scale(1.1);
        }
        &:active {
          transform: scale(1);
        }
      }
    }
  }
  .tip {
    display: none;
    margin-right: 12px;
    animation: fade 0.5s;
  }
  @media (min-width: 768px) {
    &:hover {
      background-color: #00000040;
      backdrop-filter: blur(5px);
      .tip {
        display: block;
      }
    }
  }
}
</style>

// src/components/social-links.tsx
"use client";

import { useState } from "react";
import data from "@/data/social-links.json";

export function SocialLinks() {
  const [tip, setTip] = useState("通过这里联系我吧");
  return (
    <div className="group mt-4 flex h-[42px] max-w-full items-center justify-center rounded-md transition-all hover:bg-black/40 hover:backdrop-blur md:max-w-[460px] md:justify-between animate-fade-in">
      <div className="flex flex-1 items-center justify-center md:flex-none">
        {data.map((item) => (
          <a
            key={item.name}
            href={item.url}
            target="_blank"
            rel="noreferrer"
            aria-label={item.name}
            className="focus-ring mx-3 inline-flex h-9 w-9 items-center justify-center rounded-md transition-transform hover:scale-110 active:scale-95"
            onMouseEnter={() => setTip(item.tip)}
            onMouseLeave={() => setTip("通过这里联系我吧")}
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={item.icon} alt="" height={24} width={24} className="h-6 w-6" />
          </a>
        ))}
      </div>
      <span className="hidden mr-3 animate-fade-in group-hover:block">{tip}</span>
    </div>
  );
}
